kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-job-configmap
  labels:
    app:
data:
  init.sh: |
    function generateRandomString() {
      length=${1}
      < /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-${length}};echo;
    }

    FLUENTD_URL={{ printf "%s.%s.svc.cluster.local"  .Release.Name  .Release.Namespace  }};
    sed -i 's/FLUENTD_D/'$FLUENTD_URL'/' /fluent.conf
    kubectl create configmap fluentd-conf --from-file=/fluent.conf